name: 'Terraform'
on:
  push:
    branches:
      - main
 
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env: # Define environment variables
      AWS_REGION: ap-southeast-2
 
    defaults:
      run:
        shell: bash
 
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
       
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.RACHAGOUNI_SUNITHA_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.RACHAGOUNI_SUNITHA_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
 
      - name: Prepare lambda zip files
        run: |
          zip -r lambda1.zip lambda1.py
 
      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
 
      # Format Terraform configuration files
      - name: Terraform Format
        run: terraform fmt
 
      # Plan Terraform execution
      - name: Terraform Plan
        run: terraform plan
 
      # Apply or Destroy Terraform infrastructure based on user input
      - name: Terraform Action
        run:
            terraform apply -auto-approve
           # terraform destroy -auto-approve